server:
  port: ${PORT:8081}

spring:
  application:
    name: DEMO-SERVICE

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      instance_id: ${eureka.instance.instance-id}
